### ISSUE TITLE
(Help) Building on Windows

### ISSUE THREAD

**Issue by lesscivwomp** [rdb/nim-panda3d#1]
First - thank you for this project! I hope you don't mind, but I'm having some trouble compiling the project and was hoping for some help. Thanks to many helpful members of the Nim discord, here's where we are:

When I run `make test` as the README says it runs fine up until it spits this out:

```
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpandaexpress
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpanda
...
```
(log here: https://pastebin.com/raw/amUZUrvu)

When I do `ld -LC:\Panda3D-1.10.13-x64\lib -lpandaexpress --verbose` it ends with `cannot find -lpandaexpress`. (log here: https://pastebin.com/raw/iyq68Fxb)

At the suggestion of a member, I tried `ld -LC:\Panda3D-1.10.13-x64\lib -llibpandaexpress --verbose` which passed. Based on this, I edited what gets passed to the linker as follows `-llibpandaexpress -llibpanda -llibp3dtoolconfig -llibp3dtool -llibp3direct`, but now have new `undefined reference errors` when calling `make test`: 

```
C:\Users\kc\nimcache\test_d\@m..@s..@s..@s..@s..@s.nim@snim-1.6.8@slib@ssystem.nim.cpp.o:@m..@s..@s..@s..@s..@s.nim@snim-1.6.8@slib@ssystem.nim.cpp:(.rdata$.refptr.panda_version_1_10[.refptr.panda_version_1_10]+0x0): undefined reference to `panda_version_1_10'
C:\Users\kc\nimcache\test_d\@mpanda3d@score.nim.cpp.o:@mpanda3d@score.nim.cpp:(.text+0x860): undefined reference to `BitMask<unsigned int, 32>::lower_on(int)'
C:\Users\kc\nimcache\test_d\@mpanda3d@score.nim.cpp.o:@mpanda3d@score.nim.cpp:(.text+0x870): undefined reference to `BitMask<unsigned int, 32>::bit(int)'
...
```
(log here: https://pastes.io/raw/k0xik10j7n)

Any insight would be appreciated. Thank you!

**Comment by rdb** [comment]
You have to tell nim to use MSVC. I don't think you can presently use MinGW. Maybe if you recompile Panda with MinGW, I've not tried.

To build on Windows, I use a bat file similar to this:
```bat
SET PATH=C:\Panda3D-1.10.12-x64\bin;%PATH%
nim -o:test.exe -d:"pandaDir:C:/Panda3D-1.10.12-x64" --cc:vcc cpp test.nim || exit /b
test.exe
```

Adjust the path to your Panda installation, can be the built_x64 folder of a Panda copy built from source too.

**Comment by rdb** [comment]
By the way, it's cool to see others using these bindings. I'm currently putting them to the test trying to use them in a project so they are being updated actively at the moment. Feel free to join [this Discord channel](https://discord.gg/n5sPD8ER) for discussion about these bindings.

**Comment by lesscivwomp** [comment]
> To build on Windows, I use a bat file similar to this:

Exactly what I needed! I was able to build by editing `test` in the makefile to this:
`nim -d:"pandaDir:${PANDA_DIR}" --cc:vcc cpp test.nim`

Thank you!
