### ISSUE TITLE
GeomVertexRewriter can't use GeomVertexReader functions.

### ISSUE THREAD

**Issue by janEntikan** [rdb/nim-panda3d#6]
```nim
import panda3d/core

var
  vdata = newGeomVertexData("vz", GeomVertexFormat.getV3(), GeomEnums.UH_static)
  rewriter = initGeomVertexRewriter(vdata, toInternalName("vertex"))

rewriter.setData3(6.0,5.0,4.0)
rewriter.setRow(0)
echo rewriter.getData3()
```

```
/home/olbora/Work/Panda3D/bleek/test.nim(9, 14) Error: type mismatch
Expression: getData3(rewriter)
  [1] rewriter: GeomVertexRewriter

Expected one of (first mismatch at position [#]):
[1] proc getData3(this: GeomVertexReader): LVecBase3
```

I "dimly" remember a similar problem with the lights in the very early days and had to do with casting. I added ` | GeomVertexRewriter` to all the getData* arguments which seems to have worked.  

I'm using the bindings with the disabled implicit conversion as discussed in https://github.com/rdb/nim-panda3d/issues/3 I can imagine this simply being a side-effect of that.

**Comment by rdb** [comment]
Yes, it has to do with the implicit conversion being disabled.

For now use `rewriter.upcastToGeomVertexReader.getData3()`

**Comment by rdb** [comment]
Or, modify the getData3 prototype to say `this: GeomVertexReader | GeomVertexRewriter`

**Comment by janEntikan** [comment]
Alright, in that case I'll close this to keep the discussion concentrated in issue #3
