### ISSUE TITLE
sugar for point/vector/matrix functions

### ISSUE THREAD

**Issue by janEntikan** [rdb/nim-panda3d#9]
At first glance`initLVector3f()` doesn't look to bad but it's starting to feel quite meticulous having writen it out this many times. Perhaps there can be some shorter aliasses for these functions, like maybe `vec3f()` and `point3i()`.

**Comment by rdb** [comment]
This works for me:
```nim
echo Vec3()
echo Vec3(x: 0, y: 1, z: 2)
```

**Comment by janEntikan** [comment]
Oh, how silly of me! That's just amazing. I think I just tried `Vec3(0,1,2)` and didn't read the error closely enough.
